### ISSUE TITLE
Edge is detected as Safari on iOS

### ISSUE THREAD

**Issue by keisnet** [DamonOehlman/detect-browser#105]
Hi! 

First of all, great package!

I may have found a bug regarding the use case of Edge for iOS, not entirely sure whether this issue is on your side of Microsoft's. Anyhow, here it is. 

**When using Edge for iOS:** When `detect();` is used to retrieve the name of the browser, Edge with it's user-agent of 

> Mozilla/5.0 (iPhone; CPU iPhone OS 12_1_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 EdgiOS/44.2.1 Mobile/16D57 Safari/605.1.15 

will give you a miss-leading answer, namely "ios". Although when using the user-agent that Microsoft states by changing network conditions in Chome.

> Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.2.4 (KHTML, like Gecko) Mobile/14F89 Safari/603.2.4 EdgiOS/41.1.35.1

 It will at least give you a better response, "ios-webview". 

Would be very grateful if you could look into this. 

BR

**Comment by DamonOehlman** [comment]
@keisnet Thanks for the information.  We've had a few public holidays recently in Australia and I'm currently on a short break with my family.  As soon as I'm back in Sydney I'll take a look at this.  Looking at the user agent string, we can definitely do better.

**Comment by keisnet** [comment]
@DamonOehlman Thanks for the quick reply! Enjoy the holidays!

**Comment by amok** [comment]
any news on this?

**Comment by DamonOehlman** [comment]
Apologies for the delay folks.  Any chance you can take the PR #122 for a run and see if it works for your detection?  If it's a bit of a difficult task, then I'm pretty confident that it's ok so I'll likely just :shipit:

**Comment by amok** [comment]
@DamonOehlman thanks for the fast reply

Tested on IOS MS Edge:

![image](https://user-images.githubusercontent.com/1369559/67567152-15f03500-f732-11e9-87ab-bb067c5f2ceb.png)

**Comment by DamonOehlman** [comment]
@amok thanks for testing.  Merged down the branch and published `4.8.0`
