### ISSUE TITLE
next js 

### ISSUE THREAD

**Issue by Mracobes9** [DamonOehlman/detect-browser#111]
Hi. It is working on next js ?

**Comment by DamonOehlman** [comment]
@Mracobes9 I have not tried it with Next.js.  In theory it should but if it doesn't please let me know.

**Comment by andyWynyard** [comment]
Im using this to yell at people who are using IE. Its fine.

**Comment by the-J** [comment]
Works as expected on next.js.

**Comment by DamonOehlman** [comment]
@andyWynyard @the-J thanks both for confirming it's working.  I'll close the issue.
