### ISSUE TITLE
Use with typescript

### ISSUE THREAD

**Issue by lexoyo** [DamonOehlman/detect-browser#112]
Hello
Thank you for this great lib
I can not manage to use it in silex.me which is in typescript too
Here is what i do
```sh
$ npm install --save-dev detect.js 
```
Then in the code 
```typescript
import { detect } from 'detect-browser';
``` 
And the result is `TS2307: Cannot find module 'detect-browser'.`

I also tried installing the github repo with `npm install --save-dev DamonOehlman/detect-browser `

Here is another try:

```sh
ls -l node_modules/detect-browser
total 80K
drwxrwxr-x.   2 lexoyo lexoyo 4.0K May 31 17:25 .
drwxrwxr-x. 760 lexoyo lexoyo  24K May 31 17:29 ..
-rw-rw-r--.   1 lexoyo lexoyo 1.9K Oct 26  1985 index.d.ts
-rw-rw-r--.   1 lexoyo lexoyo 5.7K Oct 26  1985 index.js
-rw-rw-r--.   1 lexoyo lexoyo 1.1K Oct 26  1985 LICENSE
-rw-rw-r--.   1 lexoyo lexoyo 2.1K May 31 17:25 package.json
-rw-rw-r--.   1 lexoyo lexoyo 4.3K Oct 26  1985 README.md
-rw-rw-r--.   1 lexoyo lexoyo  19K Oct 26  1985 yarn.lock
```
Thank you in advance for any help

**Comment by lexoyo** [comment]
As a workaround I use `import { detect } from '../../node_modules/detect-browser/index';`
I believe it is not due to detect-browser lib, but I have other modules which work fine :-/

**Comment by DamonOehlman** [comment]
@lexoyo I'm going to merge in #113 which adds the `types` field into `package.json`.  From my previous reading this shouldn't be required (as the definitions are stored in `index.d.ts`) but I'd be interested if this fixes the issue for you.

**Comment by DamonOehlman** [comment]
That PR has been merged and published in `4.5.1`.  I'll be interested to know if this fixes things for you.

**Comment by DamonOehlman** [comment]
@lexoyo Just wondering if you had any success with `4.5.1` - looking to close this issue if you did.

**Comment by singchan** [comment]
I didn't upgrade yet
I will eventually
Maybe we should close this issue and I'll reopen it if doesn't work

**Comment by lexoyo** [comment]
I didn't upgrade yet
I will eventually
Maybe we should close this issue and I'll reopen it if doesn't work
