### ISSUE TITLE
Export Typescript types for Operating System and Browser

### ISSUE THREAD

**Issue by jamzi** [DamonOehlman/detect-browser#115]
Hey!. Thanks for this package, it's a lifesaver.

I was wondering if you could export Browser and OperatingSystem types from index.d.ts, so we can use them in our apps to get better type safety, instead of just comparing strings for these values.

![image](https://user-images.githubusercontent.com/2678290/61937401-10e2e480-af8f-11e9-939b-80d0167c70ed.png)

**Comment by mdr** [comment]
Just wanted to 👍 this -- in our app we've ended up duplicating the type declarations for `Browser` and `OperatingSystem` (which can then might drift over time from the ones used by `detect-browser`).

**Comment by DamonOehlman** [comment]
Super sensible request.  I'll add those exports now and publish a new minor version.  Apologies for the delay, I'm terrible at keeping track of my issue inbox.

**Comment by DamonOehlman** [comment]
Just published `4.7.0` which includes these types exported.
