### ISSUE TITLE
CDN support required

### ISSUE THREAD

**Issue by aaabidunique** [DamonOehlman/detect-browser#124]
I have an old project which required cdn based script inclusion.
Can you please provide me cdn for the library so I can use it.
@DamonOehlman

**Comment by DamonOehlman** [comment]
@aaabidunique Sure - I've been thinking about doing this for a while.  I'll look at outputting a UMD build as part of the package and then a service like [unpkg](https://unpkg.com/) should work.

**Comment by 5punk** [comment]
For the latest package, go [here](https://unpkg.com/browse/detect-browser/)

Additionally I'll add this to the README.md as well.

Thanks for pushing for this @aaabidunique
