### ISSUE TITLE
es/index.js is not present in the published module

### ISSUE THREAD

**Issue by ashubham** [DamonOehlman/detect-browser#142]
The `package.json` mentions `module: es/index.js` as the ES Module entry point for this package.

But, the file is not present in the published package.

Version: 5.1.0

**Comment by DamonOehlman** [comment]
Thanks @ashubham - I'll get that sorted in the next 24 hours.

**Comment by DamonOehlman** [comment]
@ashubham Published `5.1.1` which has the missing file.  Let me know if that fixes things for you.  I've additionally made a change in the repo which should hopefully prevent this happening again in the future.  Thanks again for filing the issue.

**Comment by ashubham** [comment]
Thanks @DamonOehlman . Works now!
