### ISSUE TITLE
[Feature] esm specification export is required

### ISSUE THREAD

**Issue by Yiniau** [DamonOehlman/detect-browser#144]
### esm specification export is required

I'm try the solution like snowpack builder, found the rollup commonjs plugin cannot handled multi output in detect-browser( base 
 on node_modules/detect-browser/index.js )
> if it could, tell me please 🤤

there exsist es build scripts in package.json and seem to good to work too, but why ignored it in .npmignore

**Comment by DamonOehlman** [comment]
There should be as of `5.1.1` - see #143 which fixed this issue.  `5.1.0` had the issue of advertising an ESM export but it wasn't included in the package contents - originally reported in #142.

If there is a particular syntax that snowpack requires for recognising the esm module - let me know and I can take a look.

**Comment by Yiniau** [comment]
> If there is a particular syntax that snowpack requires for recognising the esm module - let me know and I can take a look.
thx, there no special writing required

i see the 5.1.1 contained es folder, THX
