### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by alanhogan** [DamonOehlman/detect-browser#145]
Updating this dependency from 5.0 to 5.1, I don’t see an easy way to see what’s new between these releases. I would especially like to see a changelog for major version bumps. Thanks

**Comment by DamonOehlman** [comment]
I'm happy to link to the releases page in the README somewhere, I tend to favour updates there rather than a separate `CHANGELOG.md` file:

https://github.com/DamonOehlman/detect-browser/releases

**Comment by alanhogan** [comment]
ah, wouldn't you know it, I did try the "tags" thing from the project root here on GH, but I didn’t see any link to Releases or check that. Thanks. 

+1 to the idea of a prominent link to this from README!

**Comment by DamonOehlman** [comment]
Added to the readme - and pretty close to the top :)
