### ISSUE TITLE
I made a demo link for you

### ISSUE THREAD

**Issue by rayshan** [DamonOehlman/detect-browser#148]
Hi! Thanks for this, works really well! So much better than the giant stackoverflow posts.

I noticed that there's no demo, so I made this: https://observablehq.com/@rayshan/browser-detection-tester-using-the-detect-browser-package. Good idea to put it in README?

**Comment by DamonOehlman** [comment]
@rayshan Absolutely - that's a fantastic idea!

Did you want to update your URL to `browser-detection` rather than the current `browswer-detection`?

**Comment by rayshan** [comment]
🤦‍♂️ fixed, it's a little long now but probably good for SEO.

**Comment by DamonOehlman** [comment]
@rayshan added to the README - thanks for putting the workbook together :)
