### ISSUE TITLE
Android Edge Chromium no longer detected

### ISSUE THREAD

**Issue by GaryHyland** [DamonOehlman/detect-browser#151]
The User Agent for this is now
Mozilla/5.0 (Linux; Android 9; SM-N950F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.116 Mobile Safari/537.36 EdgA/45.08.4.5074
This no longer matches the test. This is quite a popular browser, so would be good to recognise, pretty easy change to the test also.

**Comment by DamonOehlman** [comment]
@GaryHyland thanks for the report - I'll add a breaking test for that user agent and then fixup the regex to ensure the package provides useful output.

**Comment by DamonOehlman** [comment]
Published as `5.2.0`
