### ISSUE TITLE
Add CURL detection

### ISSUE THREAD

**Issue by franciscop** [DamonOehlman/detect-browser#160]
I'd like to suggest adding CURL support. Curl shows up as:

```
curl/7.64.1
```

So I'd like to suggest adding CURL parsing resulting in:

```js
{
  name: "curl",
  version: "7.64.1",
  os: null,
  type: "bot"
}
```

Is this okay? I can [make a PR according to the docs](https://github.com/DamonOehlman/detect-browser#adding-additional-browser-support), but was unsure about both the "os" and "type" field.

**Comment by DamonOehlman** [comment]
@franciscop I'm definitely in favour of this.  I think `null` is good for the `os` for now.  At some point I might look at converting the `null` return result to an additional literal of `unknown` but that would be for later and a major release as it would be a breaking change.  So I think what you have suggested in this issue, is perfect 👍🏻

**Comment by franciscop** [comment]
Done! Not exactly as I originally suggested, since it seems the code "guided me" to a slightly different structure, [see the PR for details](https://github.com/DamonOehlman/detect-browser/pull/161).
