### ISSUE TITLE
Major/minor version exposed for comparison

### ISSUE THREAD

**Issue by heruan** [DamonOehlman/detect-browser#17]
It would be great to have major and minor versions exposed as numbers for comparison, e.g.

``` javascript
var browser = require("detect-browser");

console.log(browser.name); // "chrome"
console.log(browser.version); // "51.0.2704"
console.log(browser.major); // 51
console.log(browser.minor); // 0
console.log(browser.patch); // 2704

if (browser.major < 50) {
    console.error("You need version 50.x.x or above!");
}
```

**Comment by DamonOehlman** [comment]
Sounds like a good idea to me - I'll take a look at what is required to get this done.  One question, in particular browsers (Firefox is one example I think), there is no patch version in the browser information.  What would you expect here?   My preference would be to set the patch value to 0 as I think I believe it's safe to infer that anyway.

**Comment by heruan** [comment]
You're right, obviously we're talking about conventions on version numbering. I think the parsing should be best effort, something like:
```javascript
var split = browser.version.split(".");
switch (split.length) {
    case 3: browser.patch = parseInt(split[2], 10);
    case 2: browser.minor = parseInt(split[1], 10);
    case 1: browser.major = parseInt(split[0], 10);
}
```
then we would have:

| `version`  | `major` | `minor` | `patch` |
| ---------- | -------: | -------: | -------: |
| `"51.0.2704"` | `51` | `0` | `2704` |
| `"45.3"` | `45` | `3` | `undefined` |
| `"1.0.0-beta.3"` | `1` | `0` | `NaN` |

and I think this could be easily handled such as `if (browser.patch && browser.patch > 2700)`, since either `undefined` and `NaN` are falsy values.

**Comment by DamonOehlman** [comment]
I the `1.0.0-beta.3` case do you think we should just return the string value in cases where it fails?  Or maybe selectively if there is a `-` character in the string?  I kind of feel bad having `NaN` returned.  I think `undefined` makes sense when it doesn't exist as it gives you more information than returning `0` in it's place.

**Comment by cadichris** [comment]
In case the `browser.version.split(".").length` is equal to 3 (i.e. the `version` *is* semver-compliant), you may use https://github.com/npm/node-semver to express your requirements.

For instance something like `semver.satisfies(browser.version, '>=50.x.x')`

This is not 100% related to the issue, but I figured developers looking into major/minor parsing could be interested in this method.

**Comment by B-Stewart** [comment]
Any update on this? For me, I would prefer returning either a number or `undefined`. That way I could run math operations on them such as `IE>9` and not be so worried about parsing out the string as a proper number.

**Comment by pedrodurek** [comment]
`const [major, minor] = browser.version.split('.').map(Number);`

**Comment by DamonOehlman** [comment]
Closing as I think this responsibility is best handled by another package, e.g. `semver`.  At some point I should probably consider leaving the versions that come through from the browser intact rather than reporting just the first 3 components of the version as this will limit what can be done with the information when passed to `semver`.
