### ISSUE TITLE
Detect Vivaldi

### ISSUE THREAD

**Issue by DamonOehlman** [DamonOehlman/detect-browser#18]
Today I learned about Vivaldi: https://vivaldi.com/

```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36 Vivaldi/1.2.490.43
```

**Comment by snuggs** [comment]
Nice @DamonOehlman. Thinking about taking on this PR myself since there is no traction. Would you mind? I'll be sure to go over the regexp with you but seems like a simple add to the browser mapper
https://github.com/DamonOehlman/detect-browser/blob/master/lib/detectBrowser.js#L2

However would clean up the testing architecture a touch. `**/all.js` is a little bit passé IMHO and breaks node module conventions.

Would merely rename to `index.js` at minimum

**Comment by DamonOehlman** [comment]
@snuggs that'd be awesome - thanks. Probably worth doing any test refactoring in a separate PR so it can be reviewed separately. Maybe do that one first, and we can land that and then you can tackle the vivaldi rule.

**Comment by snuggs** [comment]
Copy that chief! 💯

**Comment by snuggs** [comment]
@DamonOehlman https://github.com/DamonOehlman/detect-browser/pull/21

**Comment by snuggs** [comment]
OK We ready to handle this one now @DamonOehlman ? ;-)

**Comment by DamonOehlman** [comment]
I reckon so 👍

**Comment by snuggs** [comment]
Just got this. Laborday on it tomm.

**Comment by gdh1995** [comment]
@DamonOehlman Sorry to disturb you, but as said in https://vivaldi.com/press/releases/vivaldi-2-10-no-strings-attached/ , now Vivaldi does not put its name into userAgent any more.

**Comment by danielrussellLA** [comment]
occasionally vivaldi puts its name in `navigator.appVersion` - but it's not reliable from what i can see with my testing

**Comment by MaoliWolf** [comment]
As you mention the point that Vivaldi doesn't send userAgent, is checking the window size possible? Vivaldi has its own sidebar and bottom bar. It may return the wrong browser, but I think you can try

**Comment by DamonOehlman** [comment]
@MaoliWolf I think that is definitely something that is better left to an application to do rather than this package.  If a site really does need to know if vivaldi is being used and using `detect-browser`, then it could do some further investigation on those screen sizes.  I definitely wouldn't want to rely on it though, because screen sizes are things that change.  A LOT.
