### ISSUE TITLE
Internet explorer versions < 11 not detected in compatibility mode

### ISSUE THREAD

**Issue by Neograph734** [DamonOehlman/detect-browser#2]
This issue occured in Internet explorer 11 running in compatibility mode, emulating IE8-10. During that emulation the browser name and version were undefined. 

Root of this cause is that `navigator.userAgent` contains the part 'Trident 7' (but not Gecko), so it does not fit any of the patterns. 

Solution:
Update line 6 to `[ 'ie', /MSIE\s([0-9\.]+);.*Trident\/[4-7].0/ ],`

**Comment by DamonOehlman** [comment]
Thanks - I'll make that change in the next couple of days - unless you beat me to it with a PR :)

**Comment by Neograph734** [comment]
Created a request in #3 .
