### ISSUE TITLE
Detect "chrome for iOS"

### ISSUE THREAD

**Issue by lorro** [DamonOehlman/detect-browser#22]
When I run the module in chrome for iOS, the module returns "undefined" instead of "chrome".
Maybe something that needs to be caught too? :)

Greetings

**Comment by gsotirov** [comment]
Hi, 
I proposed a pull request with changes to the detection strings to support the above-mentioned browser (Chrome for iOS).

**Comment by DamonOehlman** [comment]
Thanks @gsotirov :)

**Comment by DamonOehlman** [comment]
Closed by #23 🍻
