### ISSUE TITLE
Detect Private browsing

### ISSUE THREAD

**Issue by CoreyCole** [DamonOehlman/detect-browser#28]

**Comment by 5punk** [comment]
@DamonOehlman 
Is this something you wanna add?
It can be done.

**Comment by DamonOehlman** [comment]
If it's something that can be done, it sounds reasonable to me.  How do you think it would look in terms of the results returned from the detection?  Do you think it would be an additional attribute (e.g. `browser.private`) or a different browser name (e.g. `chrome-ingonito`).

**Comment by 5punk** [comment]
I was thinking a Boolean flag.
Mind you, this is a javascript file on its own that checks for technical limitations on the browser to what is "normally" available to detect if Incognito is on.

It's not a perfect system, and cannot be supported by all browsers.

**Comment by 5punk** [comment]
Due to the fact that there is no standardized way to detect incognito mode, and most importantly every platform and browser has it's own irregular method of checking absence of some API function; I was thinking we shouldn't implement this.
