### ISSUE TITLE
Returning undefined in WebView on iOS

### ISSUE THREAD

**Issue by mikeebee** [DamonOehlman/detect-browser#30]
I was using `browser.name` to detect iOS. I noticed that my site crashed when being viewed from Facebook/Instagram/Twitter which uses WebView.

`TypeError: undefined is not an object (evaluating 'browser.name')`

Is this expected behaviour, or a bug?

Cheers,
Mike

**Comment by DamonOehlman** [comment]
@mikeebee I think this would definitely be classified as a bug (based on the simple documentation in the README).

I'll have a look ASAP and get back to you on that.  My guess is that particular apps customise the useragent for their applications (which [seems [quite easy](http://stackoverflow.com/questions/478387/change-user-agent-in-uiwebview-iphone-sdk)).

Unfortunately it looks like I have coded the logic of `detect-browser` to return `undefined` if no browser match is found which would be responsible for the error you are seeing.  I think a better option would be to return something like the following in the case of an unknown browser:

```js
{
  browser: 'unknown',
  version: null,
}
```

If I do make this change though, I think I'll definitely have to bump the major version as there may be some folks relying on this undocumented "feature".

**Comment by DamonOehlman** [comment]
@mikeebee I've updated the examples in the README to clearly show that an `undefined` result means the browser wasn't detected (as per my comment in #31).  Can you please take a look and see if this usage example makes sense to you?

**Comment by DamonOehlman** [comment]
Sweet - closing :)
