### ISSUE TITLE
Opera mini throws error

### ISSUE THREAD

**Issue by vladimirivanoviliev** [DamonOehlman/detect-browser#32]
When trying to detect Opera mini browser on iOS, the page is not loaded at all, possibly due to JavaScript error in the package. The UserAgent string is the following:

`Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_5 like
Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) OPiOS/14.0.0.104835 Mobile/13G36 Safari/9537.53"`

After a wild guessing that the browser is not in the list of detected browsers, I tried to add the following to the browsers list which **seems to work as expected** (the page is now loaded):

```
  var browsers = [
    [ 'opera', /OPiOS\/([0-9\.]+)(?:\s|$)/ ],
```

Should you add it to the list of supported browsers?

**Comment by vladimirivanoviliev** [comment]
Also the Opera regular browser (not mini) on iPhone reports the following UserAgent:

`Opera/9.80 (iPhone; Opera Mini/14.0.0/60.271; U; en) Presto/2.12.423 Version/12.16`

Finally if actually an error is thrown if current browser is not matched by any UA string in the list (didn't have the time to debug) I think default values should be introduced - for example `uknown browser` ...

**Comment by DamonOehlman** [comment]
@vladimirivanoviliev Thanks for reporting this, I created a PR to address this issue (where a browser is not correctly detected) - see #31.  However, the more I think about this, the more I realise it's a documentation issue.  I'll update the README now to cater for how to deal with the unknown browser case.

**Comment by DamonOehlman** [comment]
@vladimirivanoviliev I've updated the examples in the README, let me know if this makes things cleaer.
