### ISSUE TITLE
IE11 user agent string not matched

### ISSUE THREAD

**Issue by kjacobson** [DamonOehlman/detect-browser#35]
I encountered the following UA string in our logs:
`Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0; MSN 11.61; MSNbMSNI; MSNmen-us; MSNcOTH) like Gecko`
It seems to be a valid UA string for IE11 on Windows 10 Desktop per https://browscap.org/ua-lookup.

Per browsercap, it seems to be the same browser version that reports this string:
`Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; rv:11.0) like Gecko` which your RegEx _does_ match. 

I haven't figured out yet what accounts for this discrepancy, but it seems maybe the first UA string should be matched as well. This would do the trick:
`/Trident\/7\.0.*rv\:([0-9\.]+).*\).*Gecko$/`

I don't think there's any risk of false positives, though you could certainly use fewer `.*` matchers

**Comment by DamonOehlman** [comment]
Closed by #36.  Thanks again.
