### ISSUE TITLE
use a single main file instead of browser/main.

### ISSUE THREAD

**Issue by ashubham** [DamonOehlman/detect-browser#41]
It would be great if we could move to a single `main` index.js for Node/Browser. 

The browser/main distinction which we currently have in package.json does not play nicely with some module loaders (I am using SystemJS). 

It does not even seem to appear in the official npm docs https://docs.npmjs.com/files/package.json

**Comment by DamonOehlman** [comment]
Happy to investigate this.  The browser field is something that is defined by browserify, see:

https://github.com/substack/node-browserify#browser-field

I guess I'd need to get a feel for how many people are using this in both a node and browser environment within their projects (i.e. are people using the module in a isomorphic project sense and tweaking behaviour based on what `detect-browser` tells them).

**Comment by DamonOehlman** [comment]
@ashubham If you have a chance it would be great if you can have a look at the [`2.0.0`](https://github.com/DamonOehlman/detect-browser/releases/tag/v2.0.0) release as I think this should be getting close to working now.  I haven't tried it with SystemJS yet, but I expect we are a lot closer than before so can roll out patches (and hopefully some tests along with that) to get SystemJS compatibility up and running.

**Comment by ashubham** [comment]
@DamonOehlman Thanks a ton, for the changes, I had been using my fork as I only needed to use this in the browser. Will now switch to using this instead. Will close, as soon as I test this.

**Comment by DamonOehlman** [comment]
@ashubham no worries, eager to hear if it all works for you.  If it doesn't we'll keep tweaking it until it does :)

**Comment by 5punk** [comment]
Closing since it's fixed by @DamonOehlman
