### ISSUE TITLE
Facebook App 138 on iOS 10.3

### ISSUE THREAD

**Issue by JosefJezek** [DamonOehlman/detect-browser#44]
```
Mozilla/5.0 (iPad; CPU OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Mobile/14G60 [FBAN/FBIOS;FBAV/138.0.0.49.91;FBBV/69441604;FBDV/iPad4,4;FBMD/iPad;FBSN/iOS;FBSV/10.3.3;FBSS/2;FBCR/;FBID/tablet;FBLC/cs_CZ;FBOP/5;FBRV/0]
```

https://developers.whatismybrowser.com/useragents/parse/

![image](https://user-images.githubusercontent.com/2110319/29936237-bc0509aa-8e81-11e7-9521-66bc0dfb9e29.png)

**Comment by DamonOehlman** [comment]
So if `detect-browser` was to report something like the following for the facebook app, do you think that would work?

```js
{
   name: 'Facebook App',
   version: '138.0'
}
```

I might see if I can get the information from the above site from the iPhone equivalent of the app.  Just trying to work out how to provide some distinction for platforms.  I never intended the detection to include any kind of OS or platform data, so it could be that we end up:

1. Both "Facebook App (iPad)" and "Facebook App (iPhone)", or;
2. "Facebook App" and folks do some additional testing if they really need to know...

**Comment by 5punk** [comment]
Well, do we want to introduce `device_type`?

**Comment by DamonOehlman** [comment]
Undecided myself.  I don't there is any harm in it and it more correctly represents things rather than adding it to the name by default (if someone wants to construct a `switch` statement using name and device type they could use an ES6 template or similar).

I reckon `deviceType` is probably the appropriate property name, as `device_type` is quite pythonesque, and JS tends to go with camelCase more commonly.

**Comment by DamonOehlman** [comment]
Maybe `platform` is a more appropriate attribute also.  It's possible that folks might expect more detail on a property called `deviceType` which we probably wouldn't want to give as I think `detect-browser` should strive to remain a minimalist UA sniffing package.

A simple example I'm thinking of would be MS edge:

```js
{
  name: 'Edge',
  version: '15.0',
  platform: 'xbox-one'
}
```

Where platform could be values such as `xbox-one`, `win10-mobile`, `win10`, etc.

For things like iPhone and iPad, would platform values of `ios-iphone`, `ios-ipad`, `ios-appletv` (assuming that's a thing) be sufficient?  IMO we should steer clear of platform versions and attempting to determine any device detection...

**Comment by 5punk** [comment]
Yeah,
we can probably try that.

**Comment by 5punk** [comment]
Fixed.
Closing.
