### ISSUE TITLE
Feature for detecting operating system? 

### ISSUE THREAD

**Issue by winghimjns** [DamonOehlman/detect-browser#45]
Hello Damon, I have been using the detect-browser package via npm at work for couple of projects.

This package is good and easy to use, usually developers don't spend time on user agent. Before use this package, I used to search online for the regex to test the user agent string. Now this is really helpful. 

Not as complicated as I don't want it be, but still has the feature that I need.

How do you think about add a feature to detect the operating system?

```js
switch (browser.os) {
    case 'ios':
        // iOS
        break;
    case 'android':
        // android
        break;
    case 'wp':
        // windows phone
        break;
    case 'windows':
        // windows desktop
        break;
    case 'mac':
        // Mac
        break;
    case 'linux': // or even 'ubuntu', 'fedora', etc.
        break;
        // all of the other os
    default:
        // what ever
}

```

**Comment by DamonOehlman** [comment]
@winghimjns It could definitely be done, and I have thought about it a couple of times.  I've just checked the consistency of reporting the OS across safari, chrome and firefox on my machine here and it is something that could be extracted pretty reliably.  I do wonder if that's the case for most browsers across all OSes though (including mobile OSes).

@5punk this seems related to #44 so I was wondering what your thoughts on this were.  Do we look at introducing device / os detection as an alpha feature?

**Comment by 5punk** [comment]
@DamonOehlman 
I can pick this up.
