### ISSUE TITLE
Opera browser is not detected

### ISSUE THREAD

**Issue by hhovakimyan** [DamonOehlman/detect-browser#50]
I receive this user agent from one of  my clients
`Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36 OPR/48.0.2685.52 (Edition Campaign 34)`
And `detect-browser` package can not detect browser with this user agent. I use version 2.0.0

**Comment by 5punk** [comment]
Alright.
Let's have a look see.

**Comment by mois-ilya** [comment]
`Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36 OPR/34.0.2036.25 (Edition Yx 01)`

New RegExp for OPR userAgent
`/OPR\/([0-9\.]+)[\s]*?(\(.*\)|$)$/`

**Comment by DamonOehlman** [comment]
Cleaning up issues, this looks to be fixed in #103.  Validated that there is a test for a similar user agent to the one supplied above:

https://github.com/DamonOehlman/detect-browser/blob/master/test/logic.js#L135-L139
