### ISSUE TITLE
Can we export browsers name into constants?

### ISSUE THREAD

**Issue by dchhetri** [DamonOehlman/detect-browser#51]
It would be nice if we could do something like 
````javascript
import { detect, browserNames } from 'detect-browser';
const browser = detect();

function foo() {
  switch(browser.name) {
    case browserNames.chrome: doChrome(); break;
    case browserNames.ie: doIE(); break;
  }
}
````

**Comment by DamonOehlman** [comment]
That doesn't seem unreasonable to me, though if you are considering using TypeScript (see bindings [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/detect-browser/index.d.ts)) or Flow (I should write some bindings), you get the benefit of string literal union types (see below from the typescript binding):

```typescript
export type BrowserName =
    "android" |
    "bb10" |
    "chrome" |
    "crios" |
    "edge" |
    "firefox" |
    "fxios" |
    "ie" |
    "ios" |
    "kakaotalk" |
    "opera" |
    "phantomjs" |
    "safari" |
    "vivaldi" |
    "yandexbrowser";
```

This would provide you a better layer of protection than the constants would, and while I'm not sure (not a TypeScript user myself) it's quite possible the code completion in various editors would work...

Something for me to investigate.

**Comment by 5punk** [comment]
enums are a great feature.
We should definitely consider @types/detect-browser

Closing because we will track this feature request in a new architecture story
