### ISSUE TITLE
Opera-mini

### ISSUE THREAD

**Issue by Globik** [DamonOehlman/detect-browser#53]
Is opera-mini can be detected with this module?

**Comment by udos** [comment]
just happened to take a look at this package and this issue.

looking at the code (line 115)
https://github.com/DamonOehlman/detect-browser/blob/c15fcb934d721966b972a07c7c22954afc341b25/index.js#L115

it does not appear to explicitly identify _Opera Mini_. it will just identify the browser as _opera_.

note (maybe useful for @DamonOehlman in case he wants to extend _Opera Mini_ identification): https://dev.opera.com/articles/opera-mini-request-headers/

**Comment by Globik** [comment]
@udos  I see. Last time I figured out opera-mini is not what I need to detect.
For example, mobile devices, their OS, Platform, Version is a need to detect.
A device os Android 4.3 has opera-mini but with webkit build. So no need any more in detecting mini. As this gives nothing per se.

**Comment by 5punk** [comment]
This should be available in `v3` of detect-browser.

Please reopen the issue if this is not the case for opera-mini
