### ISSUE TITLE
Can't resolve `os` in file [index.js]

### ISSUE THREAD

**Issue by shengshiqi** [DamonOehlman/detect-browser#54]
in line 73, required module `os`, but not found in package.json.

**Comment by shengshiqi** [comment]
node version: 7.6.0, package bundlers: FIS, TERMINAL print  [WARNI] Can't resolve `os` in file [/node_modules/detect-browser/index.js], did you miss `npm install os`?

**Comment by markgoho-EDT** [comment]
Getting this as well in an Angular project. v6

**Comment by DamonOehlman** [comment]
Looks like I need to perform a better "is node" check.  Currently the test is:

```
var isNode = typeof navigator === 'undefined' && typeof process !== 'undefined';
```

Which seems to be firing false positives in particular environments (Angular v6 being one example).  Alternatively, perhaps I should consider removing the ability to detect if the code is running on the server at all.  I doubt it's being used by many people and as long as it's done in a major version bump that should be acceptable.

I'd prefer that you don't have to add a workaround like adding `os` as a dev dep to your project.

**Comment by damsorian** [comment]
I have the same issue

**Comment by edaniels** [comment]
@DamonOehlman do you think you can release a major version bump for this this month? Thanks!

**Comment by edaniels** [comment]
Thanks!

**Comment by 5punk** [comment]
Closing as inactive.
