### ISSUE TITLE
Facebook & Instagram In-App Browsers Not Recognized

### ISSUE THREAD

**Issue by thetrevorharmon** [DamonOehlman/detect-browser#56]
Facebook and Instagram both use custom user-agent strings that don't match any of the pattern checks, even though they use a Safari-based or Chrome-based rendering engine. Here are the user-agent strings:

**Facebook for iOS:**
`Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_5 like Mac OS X) AppleWebKit/604.5.6 (KHTML, like Gecko) Mobile/15D60 [FBAN/FBIOS;FBAV/157.0.0.42.96;FBBV/90008621;FBDV/iPhone9,1;FBMD/iPhone;FBSN/iOS;FBSV/11.2.5;FBSS/2;FBCR/Verizon;FBID/phone;FBLC/en_US;FBOP/5;FBRV/0]`

**Instagram for iOS:**
`Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_5 like Mac OS X) AppleWebKit/604.5.6 (KHTML, like Gecko) Mobile/15D60 Instagram 31.0.0.14.97 (iPhone9,1; iOS 11_2_5; en_US; en-US; scale=2.00; gamut=wide; 750x1334)`

**Instagram for Android:**
`Mozilla/5.0 (Linux; Android 7.0; SM-G930P Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/64.0.3282.137 Mobile Safari/537.36 Instagram 30.0.0.12.95 Android (24/7.0; 480dpi; 1080x1920; samsung; SM-G930P; heroqltespr; com; en_US; 89867442)`

(I wasn't able to get a string for the Android Facebook user agent, but I figure that shouldn't be too hard to track down?)

I didn't know that the user agent string was different, so I wasn't handling nulls in my application (which I have). I figure that this might be handy to add in a future release so that it doesn't throw a null but instead recognizes the agent correctly.

**Comment by DamonOehlman** [comment]
@tdharmon thanks for the logging the report with detailed user agents.  I'll look at adding these in as soon as I can.  Apologies for taking a while to respond to the issue.

**Comment by TimAstier** [comment]
Also facing this issue.

I found only a few resources about how to detect FB in-app browser.
I tried this but without great success so far:

```
const isFacebookApp = () => {
    const ua = navigator.userAgent || navigator.vendor || window.opera;
    return (ua.indexOf('FBAN') > -1) || (ua.indexOf('FBAV') > -1);
  };
```

A solution embedded into this package would be awesome!
