### ISSUE TITLE
Supporting of WebView in iOS application

### ISSUE THREAD

**Issue by winghimjns** [DamonOehlman/detect-browser#66]
Hi, I am happy to open my second issue post here and helping to improve this package again.

I am a web developer and I am reported that a client found the web page "doesn't work" (that's how they usually explain  ¯\_(ツ)_/¯ ). 

I finally realised the issue is when the website is opened in iOS mobiles WebView (LinkedIn and Instagram in my case), `const browser = detect()` is getting`null` instead of an object and it's obviously throwing error when I try to access `browser.version`. (FYI: I tried LinkedIn and Instagram)

So I have 2 suggestions and hope to see how's your thoughts about this:

1. Make a default value for "unknown browser", `{os: "iOS", name: "unknown" version: "unknown"}` instead of null.
1. Build the detection for iOS native app's WebView, `{os: "iOS", name: "ios-webview", version: ...}`.

**Comment by DamonOehlman** [comment]
@winghimjns Definitely keen to have you submit a PR :)

My preference is to go with option 2.  Thanks to @Enijar for the investigation you should be able to do something similar to what is suggested above.  You'd need to update the regex so it would extract the version number also, and I'm happy to help with that on the PR itself.

Additionally, when using attempting to use the struct returned by detect, e.g.

```js
const browser = detect();
```

I would alway make sure it is a non-null "truthy" value before using it.  The reason `null` is used to give you a quick way to detect that a browser has not successfully been detected.  The code samples in the README provide a bit more detail on this.

**Comment by Enijar** [comment]
@DamonOehlman I've sent you a [Pull Request](https://github.com/DamonOehlman/detect-browser/pull/67).

**Comment by DamonOehlman** [comment]
@winghimjns resolved by #67 courtesy of @Enijar
