### ISSUE TITLE
[REFACTOR] v4 detect-browser

### ISSUE THREAD

**Issue by 5punk** [DamonOehlman/detect-browser#72]
Below is a list of requests we wish to focus on for our user base, followed by a list of potential solutions that can solve those requirements.
This list will constantly be updated and modified based on the comments and input from the community.

## Feature requests:

- [ ] Types
- [ ] Export set of BrowserNames, OS the package can detect (Enums)
- [ ] Handling consumption in multiple ways (amd / cjs / es6)

### Solutions:

* Typescript
* UMD build targets
* Module builds
* Rollup Plugin build
* es6 port

#### Nice to haves

* Functional Programming
* Modular breakdown of file / folder structure

**Comment by 5punk** [comment]
@DamonOehlman

**Comment by DamonOehlman** [comment]
@5punk Again sorry for the delay - especially when I've only got such a short response:

"All sounds great"

I think the highest priority is definitely the UMD build targets.  Happy for whatever source language / structure changes too.

**Comment by DamonOehlman** [comment]
@5punk I've closed this as I think we hit the critical items on the list.  Feel free to create separate issues for any of the items that we didn't address (e.g. a UMD build).
