### ISSUE TITLE
TypeScript support?

### ISSUE THREAD

**Issue by sargant** [DamonOehlman/detect-browser#74]
Hello, would there be any interest in TypeScript typings for this project? I'm willing to write them myself, but in terms of ongoing support, would they be better off within this repo, or in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)?

**Comment by DamonOehlman** [comment]
@sargant I think TypeScript typings would be excellent.  More than happy for them to be maintained as part of the project.  Ideally with some kind of test as part of the travis job to make sure they haven't gone out of sync with the API (I've no idea if this is possible - just thinking out loud).

I'm taking a few weeks off at the moment renovating a house for sale, but checking in regularly.  I'm sure either myself or @5punk will be happy to merge it once you've done all the hard work ;)

**Comment by themaawaa** [comment]
Defo interested in typescript support

**Comment by carusology** [comment]
h/t @DamonOehlman 

If you write it, I'll give it a review. Thanks for creating a helpful module.

**Comment by brianmriley** [comment]
I'd be more than happy to review as well.

**Comment by DamonOehlman** [comment]
PR available in #79 for any interested parties.

**Comment by centigrade-thomas-becker** [comment]
#79 has been merged - this issue should be closed

**Comment by DamonOehlman** [comment]
@centigrade-thomas-becker Agreed - Typescript support has been implemented and available since `4.0.0`.  Closing the issue.
