### ISSUE TITLE
detect react-native environment

### ISSUE THREAD

**Issue by contra** [DamonOehlman/detect-browser#8]

**Comment by xiaobuu** [comment]
react-native exposes navgator.product as ReactNative

**Comment by DamonOehlman** [comment]
@xiaobuu @matthisk any version information included anywhere as part of navigator information at all that we can use?

**Comment by mausworks** [comment]
Sorry for bumping this very old issue. 

I'm using your plugin for a library which is used in both NodeJS and browser-applications, and its working great, thank you! 😄 

However, when calling `detect` in React Native, `null` is returned. 

**Is react native in scope?**

If so, I can have a look at what information is readily available, and submit a PR detect `ReactNativeInfo`.

**Comment by DamonOehlman** [comment]
@mausworks Thanks for the offer of the PR.  I think if we are able to provide react native detection with minimal overhead then it definitely makes sense.

**Comment by DamonOehlman** [comment]
Rereading the issue history I can see that it should be as simple as checking `navigator.product`, so yes I definitely think `detect-browser` should support it.

**Comment by DamonOehlman** [comment]
@mausworks Just wondering if you had any luck on a PR?  No pressure from my side, was just going through issues and cleaning ones I could up.

**Comment by DamonOehlman** [comment]
A bit thanks to @pedrouid who has killed off the longest lived issue in the repo through PR #137.  React native detection should now work in `5.1.0`.
