### ISSUE TITLE
IE 11 - Object doesn't support property or method 'find'

### ISSUE THREAD

**Issue by limonte** [DamonOehlman/detect-browser#89]
The IE11 build on AppVeyor is failing after updating from 3.0.1 to 4.0.2: https://github.com/sweetalert2/sweetalert2/pull/1358

The build log: https://ci.appveyor.com/project/limonte/sweetalert2/builds/21457395

**Comment by DamonOehlman** [comment]
Thanks for finding and reporting these.

**Comment by DamonOehlman** [comment]
Published `4.0.3` (hopefully this is the last one).  I think switching the `tsconfig.json` file to only expecting `es5` constructs in the code will be a big help.

**Comment by limonte** [comment]
All good now, thank you @DamonOehlman
