### ISSUE TITLE
detect crosswalk environment

### ISSUE THREAD

**Issue by contra** [DamonOehlman/detect-browser#9]
![](https://crosswalk-project.org/assets/cordova-with-devtools.jpg)

**Comment by DamonOehlman** [comment]
Looks like crosswalk is dead:

> Crosswalk is an app runtime based on Chromium/Blink.
> 
> It is an open source project started by the Intel Open Source Technology Center (http://www.01.org)
> 
> As of February 2017, Crosswalk is not being developed anymore. The last Crosswalk relase is 23.

Will close this.
