### ISSUE TITLE
tsconfig.json: Syntax Error

### ISSUE THREAD

**Issue by jerroydmoore** [DamonOehlman/detect-browser#91]
I'm using this package with gatbsyJS. Ever since adding this package to my project, the following syntax error reported:

```
 WAIT  Compiling...                                                                                                                                                11:26:27 AM

 WARNING  Compiled with 1 warnings                                                                                                                                 11:26:28 AM

 warning  in ./~/detect-browser/tsconfig.json

Syntax Error: Unexpected token } in JSON at position 212
    at JSON.parse (<anonymous>)


 @ ./~/detect-browser ^\.\/.*$
```

**Comment by DamonOehlman** [comment]
@jerroydmoore thanks for the report - I'll take a look as soon as I can.  Guess it's a good time to checkout Gatsby.

**Comment by jerroydmoore** [comment]
I think it's simply the hanging comma on [line 10](https://github.com/DamonOehlman/detect-browser/blob/3c42e74f9f47c0befd75ced0aa192476d16bf632/tsconfig.json#L10) is a syntax error for JSON files (even though its legal in JS files)

**Comment by DamonOehlman** [comment]
Sweet, that's an easy fix. Will fix and publish a patch version.

**Comment by DamonOehlman** [comment]
@jerroydmoore Done. `4.0.4` published.

**Comment by jerroydmoore** [comment]
LGTM
