### ISSUE TITLE
Xiaomi MIUI Browser support

### ISSUE THREAD

**Issue by DenisNP** [DamonOehlman/detect-browser#97]
Please add support of MIUI browser which installed on most modern Xiaomi phones.

UserAgent is like:
`Mozilla/5.0 (Linux; U; Android 7.0; en-us; MI 5 Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.146 Mobile Safari/537.36 XiaoMi/MiuiBrowser/9.0.3`

**Comment by DamonOehlman** [comment]
@DenisNP published in `4.3.0`
